GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5

###

DELETE http://localhost:3001/api/persons/5

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Added Person",
    "number": "4444-4444"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": ""
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "ss"
}

###
GET https://phonebook-deployment-etdq.onrender.com/api/persons