GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5

###

GET http://localhost:3001/api/persons/657677140d138df7d6d2398f

###

DELETE http://localhost:3001/api/persons/5

###

DELETE http://localhost:3001/api/persons/65746788db1c337a7f5c141a

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Added Person2",
    "number": "4444-4446"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "s",
    "number": ""
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "ss"
}

###

PUT http://localhost:3001/api/persons/657677140d138df7d6d2398f HTTP/1.1
content-type: application/json

{
    "name": "Added Person2",
    "number": "1111111"
}

###
GET https://phonebook-deployment-etdq.onrender.com/api/persons